[pytest]
markers =
    ui: testes de interface (Playwright)
    api: testes de API (requests)
    smoke: subconjunto rápido de testes críticos

addopts = -v --junitxml=results.xml --html=reports/report.html --self-contained-html
testpaths = tests